# 独墅湖人才公寓 / 慧湖通认证凭据
# 手机号 (11 位)
PHONE='13800000000'
# 识别号 (身份证后 8 位)
UID_VALUE='12345678'

# 客户端 ID (公共固定参数)
CLIENT_ID='6d6bc6f3b5f04107a5fc1c62e39dd5f4'

# 运营商标识:
# 中国移动: chinaMobile
# 中国电信: chinaTelecom
# 中国联通: chinaUnicom
SERVICE_NAME='chinaMobile'
